name: salary_fits_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

#UI
  flutter_svg: ^2.0.5

#Dependecy injection / Navigation
  flutter_modular: ^5.0.3

#HTTP
  dio: ^5.1.1

#State Management
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true