name: Develop CI/CD

on:
  pull_request:
    branches:
      - develop/**
    types:
      - opened

## uncomment this line to can run the action without need push
  workflow_dispatch:

jobs:
  # push:
  #   name: Create android build
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Checkout code
  #       uses: actions/checkout@v4.1.1
    
  #     - name: Setup Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2.11.0
  #       with:
  #         channel: "stable" # 'dev', 'alpha', default to: 'stable'
  #         flutter-version: "3.13.7" # you can also specify exact version of flutter

  #     - name: Download pub dependencies
  #       run: flutter pub get

  #     - name: Run tests
  #       run: flutter test --coverage


  #     # -  Desabilitado até que a questão do coverage seja resolvida 
  #     # - name: Check coverage
  #     #   uses: VeryGoodOpenSource/very_good_coverage@v2
  #     #   with:
  #     #     path: '/coverage/lcov.info'
  #     #     min_coverage: 50
  #     #     exclude: '**/*_observer.dart **/change.dart'

  #     - name: Build Android APK
  #       run: flutter build apk -t lib/main_dev.dart --release

  #     - name: Rename Artifact
  #       run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-develop-debug

  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: app-develop-debug
  #         path: build/app/outputs/flutter-apk/app-develop-debug.apk

  pull-request:
    name: Create android build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.1
            
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.11.0
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
          flutter-version: "3.13.7" # you can also specify exact version of flutter
        
      - name: Download pub dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test --coverage
        
        
    # Desabilitado até que a questão do coverage seja resolvida 
    # - name: Check coverage
    #   uses: VeryGoodOpenSource/very_good_coverage@v2
    #   with:
    #     path: '/coverage/lcov.info'
    #     min_coverage: 50
    #     exclude: '**/*_observer.dart **/change.dart'
        
      - name: Build Android APK
        run: flutter build apk -t lib/main_dev.dart --release
        
      - name: Rename Artifact
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-${{github.event.number}}-debug
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: app-$GITHUB_ISSUE_NUMBER-debug
          path: build/app/outputs/flutter-apk/app-${{github.event.number}}-debug.apk

          
