name: Develop CI/CD

on:
  push:
    branches:
      - develop

## uncomment this line to can run the action without need push
  workflow_dispatch:

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"
          
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        
      - name: Create version.txt with nuGetVersion
        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt

      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt
  
  build:
    name: Create android build
    needs: version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion

      - name: Create new file without newline char from version.txt
        run: tr -d '\n' < version.txt > version1.txt
      
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: version1.txt
      
      - name: Test ISSUE Number
        run: echo $GITHUB_ISSUE_NUMBER-debug

      - name: Update pubspec.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'pubspec.yaml'
          propertyPath: 'version'
          value: v1.0.2
          commitChange: false
      
      
      # - name: Update version in YAML
      #   run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml

      - name: Upload YAML Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pubspec
          path: pubspec.yaml

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.11.0
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
          flutter-version: "3.13.7" # you can also specify exact version of flutter

      # - name: Cache pub dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.FLUTTER_HOME }}/.pub-cache
      #     key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
      #     restore-keys: ${{ runner.os }}-pub-

      - name: Download pub dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage

    #  - name: Upload to code coverage
    #    uses: codecov/codecov-action@v4.0.0-beta.3
    #    with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    #     file: coverage/lcov.info

      - name: Build Android APK
        run: flutter build apk -t lib/main_dev.dart --release

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: apk release
          path: build/app/outputs/flutter-apk/app-release.apk

      # - name: Rename Artifact
      #   run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-$GITHUB_ISSUE_NUMBER-debug

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: app-$GITHUB_ISSUE_NUMBER-debug
      #     path: build/app/outputs/flutter-apk/app-$GITHUB_ISSUE_NUMBER-debug.apk
